[package]
name = "leptonica"
description = "Rust port of Leptonica image processing library"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
leptonica-core.workspace = true

[features]
default = []
